variables:
  # Instruct Testcontainers to use the daemon of DinD.
  DOCKER_HOST: "tcp://docker:2375"
  # Improve performance with overlayfs.
  DOCKER_DRIVER: overlay2
services:
  - docker:dind
before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - rm -f  .gradle/caches/modules-2/modules-2.lock
  - rm -fr .gradle/caches/*/plugin-resolution/
cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - .gradle/wrapper/
    - .gradle/caches/
    - .gradle/build-cache/
build:jdk11:
  image: openjdk:11-jdk
  script:
    - ./gradlew build --info --stacktrace --no-daemon
build:jdk17:
  image: eclipse-temurin:17
  script:
    - ./gradlew build --info --stacktrace --no-daemon
build:jdk21:
  image: amazoncorretto:21
  script:
    - ./gradlew build --info --stacktrace --no-daemon

